"""Mechanical RGB565 conversion of the approved background artwork."""
from pathlib import Path
from PIL import Image
import argparse
p = argparse.ArgumentParser()
p.add_argument('image', type=Path)
p.add_argument('output', type=Path)
a = p.parse_args()
image = Image.open(a.image).convert('RGB').resize((236, 104), Image.Resampling.LANCZOS)
pixels = []
for r, g, b in image.getdata():
    value = (r >> 3) << 11 | (g >> 2) << 5 | (b >> 3)
    pixels.extend((value & 255, value >> 8))
text = '// Generated by scripts/pack-arcade-dojo.py; do not hand-edit.\n'
text += 'alignas(4) static constexpr uint8_t dojo_pixels[] = {\n'
text += '\n'.join(','.join(str(v) for v in pixels[i:i+64])+',' for i in range(0,len(pixels),64))
text += '\n};\nstatic_assert(sizeof(dojo_pixels) == 236 * 104 * 2);\n'
a.output.write_text(text)
