"""Mechanical crop/resize and RGBA packing of reference-derived artwork."""
from pathlib import Path
import argparse
from PIL import Image

parser = argparse.ArgumentParser()
parser.add_argument('sheet', type=Path)
parser.add_argument('output', type=Path)
args = parser.parse_args()
sheet = Image.open(args.sheet).convert('RGBA')
args.output.mkdir(parents=True, exist_ok=True)
# Measured asset bounds in the source sheet; no visual repainting.
assets = [('title', (70, 20, 1470, 248), (140, 25)),
          ('versus', (465, 248, 1145, 712), (61, 78)),
          ('today', (70, 704, 1465, 1008), (158, 43))]
for name, bounds, size in assets:
    image = sheet.crop(bounds).resize(size, Image.Resampling.LANCZOS)
    data = image.tobytes('raw', 'BGRA')
    content = '// Generated by scripts/pack-arcade-lettering.py.\n'
    content += f'static constexpr uint8_t arcade_{name}_pixels[] = {{\n'
    content += '\n'.join(','.join(str(v) for v in data[i:i+64])+','
                         for i in range(0, len(data), 64))+'\n};\n'
    (args.output / f'arcade_{name}.inc').write_text(content)
    print(name, size, len(data))
