"""Convert the generated 6x2 artwork sheet to indexed firmware assets.

Mechanical format conversion only: poses/style are authored in the PNG.
Requires Pillow. Re-run when replacing the artwork, not during firmware boot.
"""
from pathlib import Path
import argparse
from PIL import Image

parser = argparse.ArgumentParser()
parser.add_argument('sheet', type=Path)
parser.add_argument('output', type=Path)
args = parser.parse_args()
sheet = Image.open(args.sheet).convert('RGBA')
args.output.mkdir(parents=True, exist_ok=True)
for side in range(2):
    for pose in range(6):
        x0, x1 = round(pose * sheet.width / 6), round((pose + 1) * sheet.width / 6)
        y0, y1 = round(side * sheet.height / 2), round((side + 1) * sheet.height / 2)
        frame = sheet.crop((x0, y0, x1, y1)).resize((96, 104), Image.Resampling.LANCZOS)
        indexed = frame.quantize(colors=128, method=Image.Quantize.FASTOCTREE)
        # Palette values expressed as ARGB; decoder explicitly emits BGRA bytes.
        rgba = indexed.convert('RGBA')
        palette = [0] * 128
        indices = list(indexed.getdata())
        for index, (r, g, b, a) in zip(indices, rgba.getdata()):
            palette[index] = a << 24 | r << 16 | g << 8 | b
        packed = []
        at = 0
        while at < len(indices):
            count = 1
            while at + count < len(indices) and indices[at + count] == indices[at] and count < 255:
                count += 1
            packed.extend((count, indices[at])); at += count
        name = f'arcade_frame_{side}_{pose}'
        content = '// Generated by scripts/pack-arcade-sprites.py; do not hand-edit.\n'
        content += f'static constexpr uint32_t {name}_palette[] = {{\n'
        content += ','.join(f'0x{v:08x}' for v in palette) + '\n};\n'
        content += f'static constexpr uint8_t {name}_runs[] = {{\n'
        content += '\n'.join(','.join(str(v) for v in packed[i:i+64]) + ',' for i in range(0, len(packed), 64)) + '\n};\n'
        (args.output / f'{name}.inc').write_text(content)
        print(name, len(packed) + 512, 'bytes')
