"""Mechanical atlas cell extraction; no system fonts."""
from pathlib import Path
import argparse
from PIL import Image
p = argparse.ArgumentParser()
p.add_argument('sheet', type=Path)
p.add_argument('output', type=Path)
p.add_argument('--number-sheet', type=Path)
a = p.parse_args()
image = Image.open(a.sheet).convert('RGBA')
data = bytearray()
for row in range(5):
    for col in range(10):
        source = Image.open(a.number_sheet).convert('RGBA') if row == 4 and a.number_sheet else image
        cell = source.crop((round(col*source.width/10), round(row*source.height/5), round((col+1)*source.width/10), round((row+1)*source.height/5)))
        cell = cell.resize((32, 36), Image.Resampling.LANCZOS)
        data.extend(cell.tobytes('raw', 'BGRA'))
if a.number_sheet:
    # Brush-style M, K and dot for the live TODAY number, from the original atlas.
    source = Image.open(a.number_sheet).convert('RGBA')
    for row, col in ((2,2),(2,0),(3,7)):
        cell = source.crop((round(col*source.width/10),round(row*source.height/5),round((col+1)*source.width/10),round((row+1)*source.height/5)))
        data.extend(cell.resize((32,36),Image.Resampling.LANCZOS).tobytes('raw','BGRA'))
content = '// Generated by scripts/pack-arcade-glyphs.py.\n'
content += 'static constexpr uint8_t arcade_glyph_pixels[] = {\n'
content += '\n'.join(','.join(str(v) for v in data[i:i+64])+',' for i in range(0,len(data),64))+'\n};\n'
a.output.write_text(content)
print(len(data), 'bytes')
